---
- name: Configure DHCP Server
  hosts: dhcp-server
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install DHCP server tools
      ansible.builtin.apt:
        name:
          - isc-dhcp-server
          - net-tools
          - iproute2
        state: present

    - name: Configure DHCP server interface
      ansible.builtin.lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: "^INTERFACESv4="
        line: 'INTERFACESv4="eth2"'

    - name: Deploy DHCP configuration
      ansible.builtin.copy:
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: "0600" # permiso mas seguro porque ansible-lint lo califica como risky
        content: |
          default-lease-time 86400;
          max-lease-time 691200;
          authoritative;

          subnet 192.168.57.0 netmask 255.255.255.0 {
            range 192.168.57.25 192.168.57.50;
            option routers 192.168.57.10;
            option broadcast-address 192.168.57.255;
            option domain-name-servers 8.8.8.8, 4.4.4.4;
            option domain-name "micasa.es";
          }

    - name: Restart DHCP server
      ansible.builtin.service:
        name: isc-dhcp-server
        state: restarted
        enabled: true
